# Generated by Django 4.2.5 on 2023-11-23 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentloan',
            name='paid_amount',
        ),
    ]
